defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-paginate

sass:
  style: compressed

permalink: pretty

paginate: 3
paginate_path: "/:num/"

siteName: Functionality & Reason